image: golang
pipelines:
  default:
    - step:
        script:
          - mkdir -p /go/src/bitbucket.org/stride/rolling
          - cp -R ./* /go/src/bitbucket.org/stride/rolling
          - go get -u golang.org/x/tools/cmd/goimports
          - if [[ "$(goimports -l -d .)" != "" ]]; then echo "$(goimports -l -d .)" && exit 1; fi
          - go get -u github.com/alecthomas/gometalinter
          - gometalinter --install --update
          - gometalinter --vendor --disable-all --enable=vet --enable=vetshadow --enable=golint --enable=ineffassign --enable=goconst --tests .
          - echo '# Generate coverage report and test for race conditions'
          - go test -race -cover
          - echo '# Generate a CPU benchmark'
          - go test -bench .
          - echo '# Generate a memory benchmark'
          - go test -bench . -benchmem
